from typing import Any
from collections.abc import AsyncIterator
from collections.abc import Awaitable
from collections.abc import Callable

from fastramqpi.config import ClientSettings
from typing_extensions import Awaitable
from os2mo_checker.config import get_client_settings
from os2mo_checker.autogenerated_graphql_client.client import GraphQLClient
from fastramqpi.main import construct_mo_client
import csv

class Utils:
    def get_graphql_client(self) -> GraphQLClient:
        """Get settings from config, ClientSettings, and construct a GraphQLClient."""
        settings = get_client_settings()
        mo_client = construct_mo_client(settings)
        ####################################################
        # Important proof that mo_client is an AsyncClient #
        ####################################################
        # import httpx
        # from httpx import AsyncClient

        # print(type(mo_client))
        # print(isinstance(mo_client, AsyncClient))
        graphql_client = GraphQLClient(
            url=f"{mo_client.base_url}/graphql/v30",
            http_client=mo_client,
        )
        return graphql_client

    def read_ad_csv(self, filename: str) -> list[dict[str, str]]:
        with open(filename, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f, delimiter=';')
            return list(reader)

    def get_usernames(self, ad_data: list[dict[str, str]]) -> list[str]:
        return [row["SamAccountName"] for row in ad_data]
