import asyncio
import argparse
from pprint import pprint
from os2mo_checker.moout import get_list_of_addresses_to_delete

# from sqlalchemy.pool.base import reset_commit
from os2mo_checker.autogenerated_graphql_client import GraphQLClient
from os2mo_checker.autogenerated_graphql_client import AddressFilter
from os2mo_checker.autogenerated_graphql_client import ITUserFilter
from os2mo_checker.autogenerated_graphql_client.get_address_uuuid import GetAddressUuuid
# from os2mo_checker.autogenerated_graphql_client.get_address_uuuid import GetAddressUuidResult

from os2mo_checker.utils import Utils
from functools import partial


batch_size = 5
concurrent_tasks = asyncio.Semaphore(10)

# async def process_query(query: partial):
#     async with concurrent_tasks:
#         result = await query().execute()

#         yield result

def verify_response(result: GetAddressUuuid, batch: list[str]) -> bool:
    for res in result.addresses.objects:
        current = res.current
        if current is None or current.ituser_response is None or current.ituser_response.current is None:
            return False
        if str(current.ituser_response.current.user_key) not in batch:
            return False
    return True

async def process_batch(client: GraphQLClient, batch: list[str]) -> GetAddressUuuid:
    async with concurrent_tasks:
        filter = AddressFilter(ituser=ITUserFilter(user_keys=batch))
        # print(f"Processing batch: {batch}")
        response = await client.get_address_uuuid(filter)
        verified = verify_response(response, batch)

        return response


# async def process_user(client: GraphQLClient, usernames: list[str]):
#     # tasks = [for batch in usernames]
#     batches = [usernames[i:i + batch_size] for i in range(0, len(usernames), batch_size)]
#     for batch in batches:
#         filter : AddressFilter = AddressFilter(ituser=ITUserFilter(user_keys=batch))
#         query = partial(client.get_address_uuuid, filter)
#         async for result in process_query(client, query):
#             await check_address(result)
def check_address(result: GetAddressUuuid):
    if result is not None:
        list_of_addresses_to_delete = get_list_of_addresses_to_delete()
        list_of_addresses = result.addresses.objects
        for obj in list_of_addresses:
            current = obj.current
            if current is not None and str(current.uuid) in list_of_addresses_to_delete:
                print(f"Address {current.uuid} is set for deletion")
                ad_account_current = current.ituser_response
                if ad_account_current is not None and ad_account_current.current is not None:
                    ad_account = ad_account_current.current.user_key
                    print(f"AD details: {ad_account}")
                else:
                    print("AD details: ")

        # objects = response["data"]["addresses"]["objects"]
        # if not objects:
        #     print(f"No addresses found for it_user_key: {it_user_key}")
        # else:
        #     for obj in objects:
        #         address_uuid = obj["current"]["uuid"]
        #         if address_uuid in list_of_addresses_to_delete:
        #             print(f"Address {address_uuid} for it_user_key: {it_user_key} is set for deletion")
        #             print(f"AD details: {ad_account}")

async def main(csv_file: str):
    ad_data = Utils().read_ad_csv(csv_file)
    list_of_usernames = Utils().get_usernames(ad_data)

    gql_client = Utils().get_graphql_client()
    tasks = []

    # await process_user(gql_client, list_of_usernames)
    # for i in range(0, len(list_of_usernames), batch_size):
    for i in range(0, 4, batch_size):
        batch = list_of_usernames[i:i + batch_size]
        tasks.append(process_batch(gql_client, batch))

    results: list[GetAddressUuuid | BaseException] = await asyncio.gather(*tasks, return_exceptions=True)
    for result in results:
        if isinstance(result, BaseException):
            print(f"Error: {result}")
            continue
        check_address(result)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Verify address for users")
    parser.add_argument("csv_file", help="Path to the CSV file containing user data")
    args = parser.parse_args()
    asyncio.run(main(args.csv_file))
